[test] Add a workaround for ArrayIndexOutOfBoundsException during setup
Since few days, several gerrits have been failing with
ArrayIndexOutOfBoundsException
on all SWTBot or on all SWTBot Sequence: 
> org.eclipse.swt.SWTException: Failed to execute runnable
(java.lang.ArrayIndexOutOfBoundsException: 0)
> ...
> Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
>	at
org.eclipse.sirius.tests.swtbot.support.api.AbstractSiriusSwtBotGefTestCase$1.run(AbstractSiriusSwtBotGefTestCase.java:264)

This problem is probably linked with bug 441507. But we have no idea why
this problem occurs only since few days.

Change-Id: I446f0455339eac185a8007dce8132b8ca3e1e40d
Signed-off-by: Laurent Redor <laurent.redor@obeo.fr>