[test] Make RefreshWithCustomizedStyleTests more robust
Sometimes, the test
RefreshWithCustomizedStyleTests.testShapeContainerStyleCustomization
fails with this error:
junit.framework.AssertionFailedError: The icon of the figure should
corresponds to the iconPath feature value of the customized style
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.TestCase.assertTrue(TestCase.java:192)
	at
org.eclipse.sirius.tests.swtbot.AbstractRefreshWithCustomizedStyleOnCompleteExampleTest.checkFigureAccordingToSiriusStyleProperty(AbstractRefreshWithCustomizedStyleOnCompleteExampleTest.java:602)
	at
org.eclipse.sirius.tests.swtbot.AbstractRefreshWithCustomizedStyleOnCompleteExampleTest.checkFigure(AbstractRefreshWithCustomizedStyleOnCompleteExampleTest.java:549)
	at
org.eclipse.sirius.tests.swtbot.RefreshWithCustomizedStyleTests.testSiriusStyleCustomizationFromStyleTab(RefreshWithCustomizedStyleTests.java:488)
	at
org.eclipse.sirius.tests.swtbot.RefreshWithCustomizedStyleTests.testStyleCustomization(RefreshWithCustomizedStyleTests.java:458)
	at
org.eclipse.sirius.tests.swtbot.RefreshWithCustomizedStyleTests.testShapeContainerStyleCustomization(RefreshWithCustomizedStyleTests.java:330)
	
By adding a wait condition instead of only one check, this test should
be more robust.

Change-Id: Ic639a754fd5a0d9ff28de9e092376c409df5a4a1
Signed-off-by: Laurent Redor <laurent.redor@obeo.fr>