[releng] Add Log4j in extra requirements to avoid error in CI tests
SWTBot execution on CI fails due to
java.lang.NoClassDefFoundError: org/apache/log4j/Logger

Signed-off-by: Maxime Porhel <maxime.porhel@obeo.fr>