[cleanup] Avoid Potential NPE during save
This commit avoids a potential NPE without other consequence. The
transactionalEditingDomain was null probably because the session has
been closed before.

During the leak fix of issue #18 [1], this error has been seen once on
suite launched locally:
  RunRepairTest>SiriusTestCase.tearDown:1977->SiriusTestCase.checkLogs:785
Error(s) raised during test :
org.eclipse.sirius.tests.unit.diagram.migration.RunRepairTest
. Log Plugin : org.eclipse.core.runtime
  . Error from plugin:org.eclipse.core.jobs, message: An internal error
occurred during: "Session saving"., info:
java.lang.NullPointerException: Cannot invoke
"org.eclipse.emf.transaction.TransactionalEditingDomain.getCommandStack()"
because "this.transactionalEditingDomain" is null
   . Stack trace: java.lang.NullPointerException: Cannot invoke
"org.eclipse.emf.transaction.TransactionalEditingDomain.getCommandStack()"
because "this.transactionalEditingDomain" is null
	at org.eclipse.sirius.business.internal.session.danalysis.DAnalysisSessionImpl.doSave(DAnalysisSessionImpl.java:870)
	at org.eclipse.sirius.business.internal.session.danalysis.Saver.wrappedSave(Saver.java:144)
	at org.eclipse.sirius.business.internal.session.danalysis.Saver$1.run(Saver.java:121)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2400)
	at org.eclipse.sirius.business.internal.session.danalysis.Saver.saveNow(Saver.java:118)
	at org.eclipse.sirius.business.internal.session.danalysis.Saver.save(Saver.java:95)
	at org.eclipse.sirius.business.internal.session.danalysis.DAnalysisSessionImpl.save(DAnalysisSessionImpl.java:827)
	at org.eclipse.sirius.business.internal.session.danalysis.DAnalysisSessionImpl.save(DAnalysisSessionImpl.java:822)
	at org.eclipse.sirius.business.internal.session.danalysis.SaveSessionJob.performSave(SaveSessionJob.java:91)
	at org.eclipse.sirius.business.internal.session.danalysis.SaveSessionJob.run(SaveSessionJob.java:56)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

[1] https://github.com/eclipse-sirius/sirius-desktop/issues/18